### ISSUE TITLE
scoped modules

### ISSUE THREAD

**Issue by dylang** [tobiaslabs/npm-owned-modules#2]
Doesn't seem to include scoped modules.

https://www.npmjs.com/~angular

**Comment by saibotsivad** [comment]
Oh interesting, I didn't catch that, thanks!

I'll see if I can figure it out some evening this week, but if you have a solution already I'd definitely take a pull request!

On May 17, 2016 1:33:13 PM CDT, Dylan Greene notifications@github.com wrote:

> Doesn't seem to include scoped modules.
> 
> https://www.npmjs.com/~angular
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/tobiaslabs/npm-owned-modules/issues/2

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by saibotsivad** [comment]
Since npm doesn't publish api docs to query their couchdb, it took me a while to track down. But based on the [code here](https://github.com/npm/newww/blob/master/agents/user.js) I've tracked down what the  correct HTTP request would be:

https://registry.npmjs.org/-/user/angular/package

Which yields output like so:

``` json
{
  "count": 23,
  "items": [
    {
      "scope_id": 60256,
      "name": "angular2-express-engine",
      "private": false,
      "created": "2016-01-27T15:26:34.808Z",
      "updated": "2016-01-27T15:26:34.808Z",
      "deleted": null,
      "permissions": "write"
    },
    ...
    {
      "scope_id": 115946,
      "name": "@angular/router",
      "private": false,
      "created": "2015-11-06T23:22:25.828Z",
      "updated": "2015-11-06T23:22:25.828Z",
      "deleted": null,
      "permissions": "write"
    }
  ]
}
```

So now that I know how to do it, a fix should be pretty easy!

**Comment by saibotsivad** [comment]
This has been fixed. Thanks again @dylang 👍
